# Generated by Django 3.2.4 on 2021-06-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
                ('name', models.CharField(max_length=100, verbose_name='Full name')),
                ('mobile', models.CharField(max_length=20, verbose_name='Mobile number')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
            ],
        ),
    ]
