# Generated by Django 3.2.4 on 2021-07-07 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_placed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date placed'),
        ),
    ]
