# Generated by Django 3.2.4 on 2021-07-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Placed'), (1, 'Processing'), (2, 'Shipped'), (3, 'Delivered')], default=0),
        ),
    ]
